eureka:
  instance:
    hostname: eureka-center
    appname: 注册中心
  client: 
    register-with-eureka: false # 单点的时候设置为 false 禁止注册自身
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}