server:
  port: 18443
  servlet-path: '/' # the servlet path, defaults to '/'
  #ssl:
  #  enable: true
  #  key-store: classpath:keystore_RSA
  #  key-store-password: una_key
  #  key-store-type: PKCS12
  #  key-alias: una
  #  enabled-protocols: TLSv1.2
  #  protocol: TLS
