spring:
  pid:
    file: ${app.home}/application.pid # Location of the PID file to write (if ApplicationPidFileWriter is used).
    fail-on-write-error: false # Fails if ApplicationPidFileWriter is used but it cannot write the PID file.
logging:
  config: classpath:logback.xml

app:
  home: ./ # 应用根目录
  encoding: UTF-8
  timeZoneOffset: "+8" # 时区
  stdout:
    printToConsole: false
  request: 
    out:
      uuid: true #是否需要把uuid加入到MDC中
    head:
      req-uuid-key: una-internal-head-key # uuid是否已经在请求头中存在，如果存在则使用该头的key，该功能主要适配后端的微服务