# eureka:
#   instance:
#     preferIpAddress: true
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:12001/eureka  ## 注册到 eureka 

app:
  cloud-provider:
    sharing-url: http://${app.cloud-provider.sharing-name}
    sharing-name: system-sharing
    notification-url: http://${app.cloud-provider.notification-name}
    notification-name: system-notification