server:
  port: 12101

spring:
  # h2:
  #   console:
  #     enabled: true
  #     settings:
  #       trace: true
  #       web-allow-others: true
  #     path: /h2-console
  datasource:
    # url: jdbc:h2:mem:una;DB_CLOSE_DELAY=-1
    # url: jdbc:h2:file:${app.home}/../../../../h2;AUTO_SERVER=TRUE
    # url: jdbc:h2:tcp://localhost:19092/./h2
    # driverClassName: org.h2.Driver
    url: jdbc:mysql://127.0.0.1:3306/una?allowMultiQueries=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: soli
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    config:
      enabled: false
logging:
  config: ./src/test/resources/logback-test.xml
