# eureka:
#   instance:
#     preferIpAddress: true
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:12001/eureka  ## 注册到 eureka 

spring:
  cloud:
    gateway:
      routes:
        - id: manager-provider-rete
          uri: 'lb://${app.cloud-provider.manager-name}'
          predicates: 
            - Path=/pwPolicy/**,/company/**,/user/**,/group/**,/role/**,/perm/**,/menu/**,/url/**,/conf/**

app:
  cloud-provider:
    manager-url: http://${app.cloud-provider.manager-name}
    sharing-url: http://${app.cloud-provider.sharing-name}
    manager-name: system-manager
    sharing-name: system-sharing
