DROP TABLE IF EXISTS S_COMPANY;

DROP TABLE IF EXISTS S_PW_POLICY;

DROP TABLE IF EXISTS S_CP_RECORD;

DROP TABLE IF EXISTS S_USER;

DROP TABLE IF EXISTS S_USER_GROUP;

DROP TABLE IF EXISTS S_USER_ROLE;

DROP TABLE IF EXISTS S_GROUP;

DROP TABLE IF EXISTS S_GROUP_ROLE;

DROP TABLE IF EXISTS S_ROLE;

DROP TABLE IF EXISTS S_USER_PROFILE;

DROP TABLE IF EXISTS S_PERMISSIONS;

DROP TABLE IF EXISTS S_ROLE_PERM;

DROP TABLE IF EXISTS S_MENU;

DROP TABLE IF EXISTS S_URL_PERM;

DROP TABLE IF EXISTS S_CONF;