package com.una.system.gateway;

public interface Constants {
  String LOGIN_FAIL_CODE_100 = "L00100";
  String LOGIN_FAIL_CODE_NOT_SUPPORT_TOKEN = "L00101";
  String LOGIN_FAIL_CODE_PARAM = "L00102";
  String LOGIN_FAIL_CODE_USER_NOT_FOUND = "L00103";
  String LOGIN_FAIL_CODE_PASS_NOT_MATCH = "L00104";
  String LOGIN_FAIL_CODE_USER_STATUS = "L00105";
  String LOGIN_FAIL_CODE_USER_EXPIRED = "L00106";
  String LOGIN_FAIL_CODE_USER_LOCKED = "L00107";
  String LOGIN_FAIL_CODE_OVER_SESSION = "L00108";
  String NOT_AUTHENTICATION = "A00201";
  String NO_AUTHORIZATION = "A00202";

}
